name: Build
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: make init
      - name: Check
        run: make
      - name: Build
        run: make build
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.13
